=== What to know before-hand
. You will deviate from the goal of game hacking at first, in order to thoroughly learn C. Failure to do this will result in your game hacking attempts being painful at best.

. If you've got attention problems or ADD or ADHD, use a Pomodoro timer to accomodate. My recommendation is using https://github.com/Splode/pomotroid. For stress management, a Pomodoro timer will also be helpful if you extend the long breaks for yourself.
- Don't be afraid to increase the focus time if it's too short, but do it sparingly. For ADHD, shorter focus times such as 20 minutes with 1 to 2 minute short breaks might work better.

. Spending money does not equate to better quality learning material. All the material provided here is of high quality, with no catches.

. This is specific to the Windows operating system. Linux does not make a good environment to learning game hacking, and is for those that are already well versed in it.

. Do not ever use AI to ask questions or solve your problems. It will be wrong, and you will also develop an over-reliance on it for problem solving; usage of AI will also make programming not as fun, and your imposter syndrome will be through the roof because it's true.

. It is normal to copy other people's code while learning, do not feel bad. However, be sure to document / comment on each part you didn't understand before, so that you can remember and learn from it.

. If you take major shortcuts, such as neglecting to make your own menu in favor of using ImGui, that is robbing yourself of valuable learning experiences and bloating / lowering the quality of your game hack. Do it from scratch, and if you can -- to make it easier on yourself, use the game engine's own functions such what is contained within the `IMatSystemSurface -> vgui -> ISurface` class in the Source Engine to draw your menu.

=== Let's jump straight into it
. Install Visual Studio and avoid making CMake projects: https://visualstudio.microsoft.com/
- Also install the following VS extensions:
** https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools
** https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput

. Learn the C programming language as it's vital. Please do not learn C++ at this stage. Follow along and write the programs in the book to fully understand their concepts:
- https://inria.hal.science/hal-02383654v2/file/modernC.pdf
- If you pivoted into writing your own small programs from knowledge provided by that book, which is recommended, I would reference the book and this website: https://www.cbyexample.com/

. [Optional] x64 Intel assembly knowledge is highly recommended. Do all of the challenges, and optionally write tiny programs in that assembly:
- https://pwn.college/welcome/welcome/
- https://pwn.college/computing-101/assembly-crash-course/
** Command to compile NASM code: `nasm -f elf64 asm.S -o asm.o && ld asm.o -o asm_executable` +
NASM file example: https://github.com/felikcat/game-hacking-academy/blob/master/nasm_example.S +

. [Optional] Your C knowledge can further be advanced by learning computer science staples:
- https://openstax.org/books/introduction-computer-science/pages/2-introduction

. Tools to install for game hacking:
- https://github.com/ReClassNET/ReClass.NET; be sure to compile this yourself, otherwise you'll miss out on 4 years of improvements.
- https://www.cheatengine.org/; press "Skip All" in its installer to avoid installing any of the advertisements.
- https://x64dbg.com/
- Find "IDA Pro 9.0.240925 RC1" from the official source.

. Now for the fundamentals of game hacking:
- https://gamehacking.academy/

. Learn the following C++ concepts to make future game hacking easier: https://www.learncpp.com
- Chapter 14 -> Introduction to Classes
- Chapter 15 -> More on Classes
- Chapter 25 -> Virtual Functions

. If making an aimbot or ESP, in order, read the following chapters to fully understand the math behind them:
- https://openstax.org/books/intermediate-algebra-2e/pages/4-introduction (Matrices is the important one, but do not skip the others in Chapter 4)
- https://openstax.org/books/algebra-and-trigonometry-2e/pages/9-introduction-to-trigonometric-identities-and-equations
