NOTE: Heavily a work in progress.

=== What to know before-hand
. You will deviate from the goal of game hacking at first, in order to thoroughly learn C and Intel assembly. Failure to do this will result in your game hacking attempts being painful at best.
. Spending money does not equate to better quality learning material. All the material provided here is of high quality, with no catches. +
This is an important point as there is a website that preys on people spending money for access to their materials, and scams them if they accidentally used a VPN once, or are in the belief that you are someone else (due to your IP's location).

=== Let's jump straight into it.
. Learn the C programming language as it's vital. Please do not learn C++ at this stage. Follow along and write the programs in the book to fully understand their concepts:
- https://inria.hal.science/hal-02383654v2/file/modernC.pdf
- If you pivoted into writing your own small programs from knowledge provided by that book, which is recommended, I would reference the book and this website: https://www.cbyexample.com/
. x64 Intel assembly knowledge is also vital. Do all of the challenges, and optionally write tiny programs in that assembly:
- https://pwn.college/welcome/welcome/
- https://pwn.college/computing-101/assembly-crash-course/

. Now for the fundamentals of game hacking:
- https://gamehacking.academy/
